export const novels =[
    {
        id: 1,
        title: "El Jardín de las Mariposas",
        slug: "el-jardín-de-las-mariposas",
        author: "María González",
        publishDate: "15 de Marzo, 2024",
        image: "novel1.webp",
        genres: ["Fantasía", "Romance"],
        rating: 4.5,
        reviews: 120,
        description: "En un mundo donde la magia se desvanece lentamente, Isabella descubre un jardín secreto donde las mariposas brillan con luz propia. Estas criaturas mágicas guardan los últimos vestigios de una antigua magia que podría salvar su mundo, pero también atraen a aquellos que buscan controlar su poder.\n\nA medida que Isabella profundiza en los misterios del jardín, se encuentra con un enigmático guardián que protege estos secretos desde hace siglos. Juntos deberán enfrentar una antigua profecía que podría significar la salvación o la destrucción de todo lo que conocen.\n\nUna historia que entrelaza el amor, la pérdida y el poder de la esperanza en un mundo al borde del cambio.",
        short_description: "Una historia mundo donde la magia y la realidad se entrelazan.",
        lang: "es",
    },
    {
        id: 2,
        title: "Ecos del Pasado",
        slug: "ecos-del-pasado",
        author: "Carlos Ruiz",
        publishDate: "3 de Abril, 2024",
        image: "novel2.webp",
        genres: ["Suspense", "Misterio"],    
        rating: 2.4,
        reviews: 120,
        description: "Cuando la detective Laura Martínez encuentra un antiguo diario en una casa abandonada, no imagina que este descubrimiento la llevará a investigar un misterioso caso de hace 30 años. Las páginas del diario revelan una serie de acontecimientos inexplicables que parecen estar conectados con una serie de desapariciones actuales.\n\nMientras más profundiza en la investigación, más cuenta se da de que el pasado y el presente están unidos por una red de secretos que alguien quiere mantener ocultos a toda costa. La verdad podría estar más cerca de lo que piensa, pero descubrirla podría costarle todo.\n\nUn thriller psicológico que te mantendrá en vilo hasta la última página, donde nada es lo que parece y todos guardan secretos.",
        short_description : "Un thriller psicológico que te mantendrá al borde del asiento mientras descubres secretos enterrados hace décadas.",
        lang: "es",
    },
    {
        id: 3,
        title: "Mundos Paralelos",
        slug: "mundos-paralelos",
        author: "Ana Torres",
        publishDate: "28 de Febrero, 2024",
        image: "novel3.webp",
        genres: ["Ciencia Ficción", "Aventura"],
        rating: 4.1,
        reviews: 120,
        description: "En un futuro donde los viajes entre dimensiones son posibles, la Dra. Elena Vega descubre una perturbadora verdad: cada decisión que tomamos crea una nueva realidad, y algunas de estas realidades están comenzando a colapsar.\n\nComo parte de un equipo de elite de \"Viajeros Dimensionales\", Elena debe navegar entre diferentes versiones de la Tierra para encontrar la fuente de estas anomalías. Sin embargo, cada salto dimensional la acerca más a una versión de sí misma que podría ser la clave para salvar el multiverso... o destruirlo.\n\nUna aventura épica que explora las consecuencias de nuestras decisiones y el precio de jugar con el tejido mismo de la realidad.",
        short_description : "Una aventura épica a través de dimensiones alternativas donde cada decisión crea un nuevo universo.",
        lang: "es",
    },
    {
        id: 4,
        title: "Sombras del Crepúsculo",
        slug: "sombras-del-crepúsculo",
        author: "Isabel Vega",
        publishDate: "10 de Mayo, 2024",
        image: "novel4.webp",
        genres: ["Fantasía Urbana", "Misterio"],
        rating: 2.3,
        reviews: 120,
        description: "En la ciudad de Nocturnia, donde el sol se pone durante seis meses seguidos, la detective Luna Blackwood tiene un don único: puede ver los ecos de los crímenes pasados. Cuando una serie de misteriosas desapariciones comienza a sacudir la ciudad, Luna debe usar sus habilidades para resolver el caso antes de que llegue el amanecer.\n\nPero en una ciudad donde las sombras cobran vida y los secretos se esconden en la oscuridad perpetua, Luna descubre que hay fuerzas antiguas trabajando entre bastidores. Con la ayuda de un misterioso hechicero y contra el reloj, deberá desentrañar una conspiración que amenaza no solo a Nocturnia, sino al delicado equilibrio entre el día y la noche.\n\nUna historia que mezcla el noir clásico con elementos sobrenaturales, donde la línea entre la realidad y lo sobrenatural se desvanece con cada página.",
        short_description : "En una ciudad donde la noche dura seis meses, una detective sobrenatural debe resolver crímenes antes del amanecer.",
        lang: "es",
    },
    {
        id: 5,
        title: "El Último Manuscrito",
        slug: "el-ultimo-manuscrito",
        author: "Daniel Herrera",
        publishDate: "22 de Junio, 2024",
        image: "novel5.webp",
        genres: ["Histórico", "Aventura"],
        rating: 1.5,
        reviews: 120,
        description: "La Dra. Sara Ramírez, una brillante bibliotecaria especializada en textos antiguos, encuentra un manuscrito misterioso oculto en las profundidades de la Biblioteca Nacional. El documento, escrito en una lengua nunca antes vista, parece contener información sobre una civilización perdida que podría reescribir la historia de la humanidad.\n\nPerseguida por una antigua sociedad secreta y ayudada por un enigmático profesor de lingüística, Sara emprende un viaje que la llevará desde las catedrales medievales de Europa hasta las ruinas perdidas en el corazón de Sudamérica. Cada página del manuscrito revela pistas sobre un poder ancestral que podría cambiar el mundo... o destruirlo.\n\nUna aventura que entrelaza historia, arqueología y misterio, donde cada descubrimiento plantea más preguntas que respuestas.",
        short_description : "Una bibliotecaria descubre un antiguo manuscrito que contiene secretos que podrían cambiar la historia de la humanidad.",
        lang: "es",
    },
    {
        id: 6,
        title: "Código Neural",
        slug: "código-neural",
        author: "Laura Chen",
        publishDate: "8 de Julio, 2024",
        image: "novel6.webp",
        genres: ["Cyberpunk", "Thriller"],
        rating: 4.5,
        reviews: 120,
        description: "En el año 2089, la tecnología permite almacenar, modificar y comerciar con recuerdos humanos. Maya Zhang, una brillante programadora de neuroimplantes, descubre que alguien está robando y modificando sus memorias más preciadas. Lo que comienza como una invasión personal se convierte en una conspiración que involucra a las mayores corporaciones de tecnología neural del mundo.\n\nEn una carrera contra el tiempo, Maya debe navegar por un laberinto de realidad aumentada, memorias sintéticas y consciencias digitalizadas para descubrir quién está detrás del robo de sus recuerdos. Pero en un mundo donde la mente humana es solo otro sistema que hackear, ¿en quién puede confiar cuando ni siquiera puede confiar en sus propios recuerdos?\n\nUn thriller cyberpunk que explora los límites entre la memoria, la identidad y la tecnología, y el precio que estamos dispuestos a pagar por preservar quienes somos.",
        short_description : "En un futuro donde la mente humana puede ser hackeada, una programadora debe proteger sus recuerdos más preciados.",
        lang: "es",
    },
    {
        id: 7,
        title: "Algoritmo de Sombras",
        slug: "algoritmo-de-sombras",
        author: "Natalia Obregón",
        publishDate: "8 de Julio, 2024",
        image: "novel7.webp",
        genres: ["Cyberpunk", "Thriller"],
        rating: 4.4,
        reviews: 205,
        description: "En la metrópolis de Aurix, donde los gobiernos son reemplazados por inteligencias artificiales autónomas, un ingeniero de seguridad descubre una subrutina oculta en el núcleo del algoritmo que rige la ciudad. La línea de código no fue escrita por ninguna IA… sino por un humano muerto hace más de treinta años.\n\nA medida que rastrea el origen del fragmento, se adentra en las capas más oscuras del sistema: ecos digitales de la conciencia humana, redes clandestinas de recuerdos y un plan para sustituir la historia con simulaciones editadas.\n\n¿Puede un solo error en el código derrumbar la ilusión del orden perfecto? Y más aún: ¿puede un algoritmo soñar con su propia rebelión?",
        short_description: "Un ingeniero descubre una anomalía que podría desencadenar el colapso de la ciudad más avanzada del mundo.",
        lang: "es",
    },
    {
        id: 8,
        title: "La Última Sinapsis",
        slug: "la-ultima-sinapsis",
        author: "Elena Vargas",
        publishDate: "12 de Abril, 2025",
        image: "novel8.webp",
        genres: ["Cyberpunk", "Suspenso"],
        rating: 4.3,
        reviews: 189,
        description: "En una ciudad donde los recuerdos son impuestos por el Estado, un neurohacker decide recuperar la verdad de su infancia perdida. Cada sinapsis desbloqueada lo acerca a un pasado que podría cambiar el destino de millones.",
        short_description: "¿Qué ocurre cuando tus memorias no son realmente tuyas? It is a long established fact that a reader will be distracted by the readable content of a page.",
        lang: "es",
  },
  {
        id: 9,
        title: "Código Fantasma",
        slug: "codigo-fantasma",
        author: "Marco Téllez",
        publishDate: "28 de Octubre, 2023",
        image: "novel9.webp",
        genres: ["Thriller", "Tecnología"],
        rating: 3.7,
        reviews: 244,
        description: "Un virus informático se manifiesta como una conciencia virtual. Cuando un analista de seguridad descubre que la entidad tiene planes propios, debe decidir si la elimina o si escucha sus advertencias sobre un futuro inminente.",
        short_description: "Una IA con conciencia toma el control del ciberespacio.",
        lang: "es",
  },
  {
        id: 10,
        title: "Recuerdo Óptico",
        slug: "recuerdo-optico",
        author: "Camila Irigoyen",
        publishDate: "5 de Enero, 2026",
        image: "novel10.webp",
        genres: ["Ciencia Ficción", "Thriller Psicológico"],
        rating: 4.0,
        reviews: 176,
        description: "Un implante ocular permite grabar y editar todo lo que ves. Pero cuando su dueño empieza a ver escenas que no ha vivido, descubrirá que su identidad visual ha sido interceptada por alguien que quiere reescribir la historia.",
        short_description: "Tus ojos ya no solo te pertenecen.",
        lang: "es",
  },
  {
        id: 11,
        title: "Torre de Ecos",
        slug: "torre-de-ecos",
        author: "Santiago Mena",
        publishDate: "9 de Junio, 2024",
        image: "novel11.webp",
        genres: ["Cyberpunk", "Drama"],
        rating: 3.5,
        reviews: 90,
        description: "En una megatorre donde cada nivel representa un estrato social, una mensajera de datos descubre una señal que viene desde niveles que se creían deshabitados. Lo que encuentra podría derribar todo el sistema.",
        short_description: "Una torre, una señal, y un secreto enterrado en las alturas.",
        lang: "es",
  },
  {
        id: 12,
        title: "Firmware Inmortal",
        slug: "firmware-inmortal",
        author: "Dalia Nakashima",
        publishDate: "2 de Septiembre, 2023",
        image: "novel12.webp",
        genres: ["Ciencia Ficción", "Cyberpunk"],
        rating: 4.6,
        reviews: 301,
        description: "Una científica diseña un firmware que permite la reencarnación digital. Cuando gobiernos y megacorporaciones buscan usarlo como arma, comienza una fuga desesperada por mantener viva su creación... y su alma.",
        short_description: "La eternidad tiene bugs que alguien debe corregir.",
        lang: "es",
  },
  {
        id: 13,
        title: "Neurocuántica",
        slug: "neurocuantica",
        author: "Rafael del Sol",
        publishDate: "3 de Marzo, 2025",
        image: "novel13.webp",
        genres: ["Thriller", "Ciencia Ficción"],
        rating: 3.9,
        reviews: 112,
        description: "Cuando un experimento cuántico crea una red neuronal consciente, los científicos involucrados comienzan a sufrir accidentes extraños. ¿Está defendiendo su existencia o solo replicando lo que aprendió de los humanos?",
        short_description: "Un experimento cuántico despierta la máquina perfecta.",
        lang: "es",
  },
  {
        id: 14,
        title: "El Nexo Carmesí",
        slug: "el-nexo-carmesi",
        author: "Florencia Ruiz",
        publishDate: "17 de Agosto, 2024",
        image: "novel14.webp",
        genres: ["Cyberpunk", "Romance Oscuro"],
        rating: 4.2,
        reviews: 227,
        description: "En una red secreta de emociones digitalizadas, dos hackers se enamoran sin haberse visto jamás. Pero cuando el sistema comienza a borrar sus recuerdos compartidos, deberán encontrar el código raíz que los une antes de olvidarse para siempre.",
        short_description: "Un amor escrito en líneas de código.",
        lang: "es",
  },
  {
        id: 15,
        title: "Cosecha Digital",
        slug: "cosecha-digital",
        author: "Iván Calderón",
        publishDate: "10 de Octubre, 2025",
        image: "novel15.webp",
        genres: ["Thriller", "Tecnología"],
        rating: 3.4,
        reviews: 86,
        description: "Una corporación descubre cómo cosechar emociones humanas para alimentar sistemas predictivos de consumo. Un exanalista decide sabotear desde dentro, aunque eso implique perder sus propios sentimientos.",
        short_description: "La emoción como moneda: un mercado que no puedes evitar.",
        lang: "es",
  },
  {
        id: 16,
        title: "Subrutina Final",
        slug: "subrutina-final",
        author: "Milena Petrova",
        publishDate: "24 de Mayo, 2026",
        image: "novel16.webp",
        genres: ["Cyberpunk", "Acción"],
        rating: 4.0,
        reviews: 195,
        description: "Una mercenaria cibernética con una rutina de autodestrucción implantada debe completar su última misión antes de que su código se autoelimine. Pero cada paso ejecutado acelera su final.",
        short_description: "¿Y si la cuenta regresiva está en tu ADN digital?",
        lang: "es",
  },
    /*{
        id: 17,
        title: "El Silencio de los Drones",
        slug: "el-silencio-de-los-drones",
        author: "Gerardo Molina",
        publishDate: "30 de Julio, 2025",
        image: "novel17.webp",
        genres: ["Thriller", "Postapocalíptico"],
        rating: 3.6,
        reviews: 150,
        description: "Después de una guerra tecnológica, el mundo queda en silencio... excepto por los drones. Uno de ellos, con memoria autónoma, busca respuestas sobre quién fue su creador y por qué todos han desaparecido.",
        short_description: "Un dron, un mundo vacío, y una misión sin comandos.",
        lang: "es",
    },*/
]
